[package]
name = "holiday_jp"
version = "0.1.1"
authors = ["camelmasa <camelmasa@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
yaml-rust = "0.4.5"
time = "0.2.26"

[lib]
name = "holiday_jp"
path = "./src/lib.rs"
