[package]
name = "holiday_jp"
version = "0.1.0"
authors = ["camelmasa <camelmasa@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
chrono = "0.4"
yaml-rust = "0.4"

[lib]
name = "holiday_jp"
path = "./src/lib.rs"
